---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zulip-rabbitmq-data
  namespace: zulip
  labels:
    app.kubernetes.io/name: zulip
    app.kubernetes.io/component: rabbitmq
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
