---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zulip-data
  namespace: zulip
  labels:
    app.kubernetes.io/name: zulip
    app.kubernetes.io/component: zulip
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
